netgen_layouts:
  pagelayout: 'base.html.twig'

  value_types:
    doctrine_recipe:
      name: Recipe
      manual_items: true

  query_types:
    latest_recipes:
      name: Latest Recipes

  block_definitions:
    list:
      view_types:
        one_by_two:
          name: 1x2 Featured Grid
        grid:
          item_view_types:
            skill_big_view:
              name: Skills Big View

  view:
    item-view:
      # app = admin
      app:
        # this key is not important
        recipes_app:
          template: 'nglayouts/admin/recipe_item.html.twig'
          match:
            item\value_type: 'doctrine_recipe'
      # default = frontend
      default:
        # this key is not important
        recipes_default:
          template: 'nglayouts/frontend/recipe_item.html.twig'
          match:
            item\value_type: 'doctrine_recipe'
        contentful_entry/skill:
          template: '@nglayouts/item/contentful_entry/skill.html.twig'
          match:
            item\value_type: contentful_entry
            contentful\content_type: skill
        contentful_entry/ad:
          template: '@nglayouts/item/contentful_entry/add.html.twig'
          match:
            item\value_type: contentful_entry
            contentful\content_type: advertisement
      ajax:
        # this key is not important
        recipes_default:
          template: 'nglayouts/frontend/recipe_item.html.twig'
          match:
            item\value_type: 'doctrine_recipe'
    block_view:
      app:
        list/one_by_two:
          template: '@NetgenLayoutsStandard/app/block/list/grid.html.twig'
          match:
            block\definition: list
            block\view_type: one_by_two
      default:
        list/one_by_two:
          template: '@nglayouts/block/list/one_by_two.html.twig'
          match:
            block\definition: list
            block\view_type: one_by_two
