netgen_layouts:
  pagelayout: 'base.html.twig'

  value_types:
    doctrine_recipe:
      name: Recipe
      manual_items: true

  query_types:
    latest_recipes:
      name: Latest Recipes

  view:
    item-view:
      # app = admin
      app:
        # this key is not important
        recipes_app:
          template: 'nglayouts/admin/recipe_item.html.twig'
          match:
            item\value_type: 'doctrine_recipe'
      # default = frontend
      default:
        # this key is not important
        recipes_default:
          template: 'nglayouts/frontend/recipe_item.html.twig'
          match:
            item\value_type: 'doctrine_recipe'
        contentful_entry/skill:
          template: '@nglayouts/item/contentful_entry/skill.html.twig'
          match:
            item\value_type: contentful_entry
            contentful\content_type: skill
        contentful_entry/ad:
          template: '@nglayouts/item/contentful_entry/add.html.twig'
          match:
            item\value_type: contentful_entry
            contentful\content_type: advertisement
      ajax:
        # this key is not important
        recipes_default:
          template: 'nglayouts/frontend/recipe_item.html.twig'
          match:
            item\value_type: 'doctrine_recipe'
